// USERS

// ACTIONS
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const CHECK_AUTHENTICATION = 'CHECK_AUTHENTICATION';
export const ATTEMPT_REAUTHENTICATION = 'ATTEMPT_REAUTHENTICATION';

// MUTATIONS
export const SET_USER = 'SET_USER';

// CONTENT

// ACTIONS
export const UPLOAD_CONTENT = 'UPLOAD_CONTENT';
export const LOAD_MORE_CONTENT = 'LOAD_MORE_CONTENT';
export const SELECT_CONTENT = 'SELECT_CONTENT';

// Mutations
export const ADD_CONTENT_TO_LIST = 'ADD_CONTENT_TO_LIST';
export const SET_SELECTED_CONTENT = 'SET_SELECTED_CONTENT';
